services:
  postgres:
    image: postgres:16
    container_name: orders-api-postgres
    environment:
      POSTGRES_DB: ordersdb
      POSTGRES_USER: orders
      POSTGRES_PASSWORD: orders
    ports:
      - "5432:5432"
    volumes:
      - orders_api_pgdata:/var/lib/postgresql/data

volumes:
  orders_api_pgdata:
